apiVersion: apps/v1
kind: Deployment
metadata:
  name: ersm-deployment
  labels:
    app: ersm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ersm
  template:
    metadata:
      labels:
        app: ersm
    spec:
      containers:
      - name: ersm
        image: {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ersm-service
spec:
  selector:
    app: ersm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP