apiVersion: apps/v1
kind: Deployment
metadata:
  name: ersm
  labels:
    app: ersm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ersm
  template:
    metadata:
      labels:
        app: ersm
    spec:
      containers:
        - name: ersm
          image: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/ersm:latest  # Replace with your actual image if different
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: LOG_LEVEL
              value: "debug"
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ersm
  labels:
    app: ersm
spec:
  selector:
    app: ersm
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
